### ISSUE TITLE
Error running command under Windows

### ISSUE THREAD

**Issue by xsxz01** [saru-tora/anansi#7]
Hello, the author, this framework does not perform well under Windows. Running the command crashed. My operating system is Windows 11 Professional Edition, and the version number is 22621.674.

The following error is reported when creating a website, although some files seem to be able to be created
`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 3, kind: NotFound, message: "系统找不到指定的路径。" }', C:\Users\qq150\.cargo\registry\src\github.com-1ecc6299db9ec823\ananc-0.4.0\src\main.rs:281:77
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
`

The following errors are reported when running the website
`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\qq150\.cargo\registry\src\github.com-1ecc6299db9ec823\ananc-0.4.0\src\main.rs:256:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

**Comment by saru-tora** [comment]
I tried to change the way paths are handled. Hopefully, it should work now.
